# Generated by Django 3.2.3 on 2021-05-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guitar',
            old_name='bodyType_text',
            new_name='body_type',
        ),
        migrations.RenameField(
            model_name='guitar',
            old_name='brand_text',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='guitar',
            old_name='series_text',
            new_name='series',
        ),
        migrations.RemoveField(
            model_name='guitar',
            name='averagePrice_float',
        ),
        migrations.AddField(
            model_name='guitar',
            name='average_price',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
