# Generated by Django 3.2.3 on 2021-05-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_guitar_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=200)),
                ('max_speed', models.IntegerField(default=100)),
                ('average_price', models.FloatField(default=2000.0)),
            ],
        ),
        migrations.CreateModel(
            name='Soda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=200)),
                ('average_price', models.FloatField(default=2000.0)),
            ],
        ),
    ]
